### PR TITLE
fix: integrate web3auth in demo app

### PR DESCRIPTION
**Pull request by bengobeil**
### Description
As per previously discussed, integrate new web3auth package in demo app. I added React as a dependency, since demo it is executed as opposed to being a package, wouldn't work otherwise.

### Checklist
- [x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x] Check the box that allows repo maintainers to update this PR
- [x] Test locally to make sure this feature/fix works
- [x] Run `yarn check-all` to confirm there are not any associated errors
- [x] Confirm this PR passes Circle CI checks
- [x] Add or update relevant information in the documentation

### Docs Checklist
- [x] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
- [x] Add/update the appropriate package README (if applicable)
- [x] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) (if applicable)
- [x] Add/update the related package in the `docs/package.json` file (if applicable)

### If this PR includes changes to add an injected wallet or SDK wallet module: 
Please complete the following using the internal demo package.
To run this demo use the command `yarn && yarn dev` to get the project running at `http://localhost:8080/`

#### Tests with demo app (injected)
- [ ] send transaction
- [ ] switch chains
- [ ] sign message
- [ ] sign typed message
- [ ] disconnect

#### Tests with demo app (SDK)
- [x] send transaction
- [x] switch chains
- [x] sign message
- [x] sign typed message
- [x] disconnect

### CODE REVIEW

**Comment by bengobeil** [comment]
image
image

**Comment by bengobeil** [comment]
@Adamj1232 ready for review

**Review by Adamj1232 — APPROVED** [review]
Changes look good! I updated the docs to reflect the new init options. Thanks again!

**Comment by bengobeil** [comment]
Hey @Adamj1232, it seems as though calling `setChain` on the `useSetChain` hook when connected to web3auth wallet does not update the provider in the `useConnectWallet` hook. I'm not familiar with the codebase enough to fix this, I've been taking a look at day and it seems as though web3auth is not integrate with the rx/js based state, not sure about this. Would it be possible to take a look and point me in the right direction?

**Pull request merged**
