### PR TITLE
[README Updates] Change RPC Provider to Alchemy for better data consistency and reliability

### PR DESCRIPTION
**Pull request by avasisht23**
### Description
Change RPC Provider to Alchemy in the README's so users can onboard with better data consistency and reliability.

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [ ] I have run `yarn type-check` & `yarn build` to confirm there are not any associated errors --> Note: type-check errors were already present before my fork
- [ ] This PR passes the Circle CI checks

### CODE REVIEW

**Comment by Adamj1232** [comment]
Hi @avasisht23 thanks for the PR. 
Can you provide more clarity on why you want this change merged? 
Do you work with alchemy?

**Comment by Adamj1232** [comment]
@avasisht23 friendly ping on the above question regarding this change

**Comment by avasisht23** [comment]
Hi @Adamj1232 Thank you for the ping!

Yes, I work at Alchemy. I focus on developer education and community! Big fan, love what you guys are doing at Blocknative My goal with these couple of submissions is to add useful content to make the articles more educational, clear, and beneficial to users they onboard to Blocknative. 

We believe those users will benefit by default using a more reliable RPC endpoint. We've run a bunch of tests on data consistency and reliability, which you can read more about [here](https://www.alchemy.com/blog/data-accuracy). You can also try it out in real-time [here](https://benchmark.alchemyapi.io/).

Here’s a graphic showing the results from 1M queries using this tool:
telegram-cloud-photo-size-1-5100775900751964908-y

Pls feel free to share any additional feedback on how I can make my PRs better for the community :) Appreciate you taking the time to review, and appreciate what you guys do for the web3 ecosystem! Thanks!

**Comment by Adamj1232** [comment]
@avasisht23 thank you for the information! Looks positive! Will discuss this further with the team on how to properly document RPC usage while being neutral. If interested would like to put you/your teams business development contact in touch with ours for possible future changes and to explore marketing opportunities. Let me know what you think and if interested please get in touch with Shen our bizDev lead at shen@blocknative.com!

**Comment by Adamj1232** [comment]
Closing in favor of #1214 
Updated official docs to show this as well [example](https://docs.blocknative.com/onboard/core#initialization-example)
Thanks again and feel free to reach out for any partnership ideas between BN and Alchemy!

**Pull request closed without merging**
