### PR TITLE
feature: add Phantom to web3-onboard

### PR DESCRIPTION
**Pull request by bfriel**
### Description
Hey Blocknative team!

Opening this PR on behalf of [Phantom](https://phantom.app/). We are currently in closed-beta and several dapps want to participate with web3-onboard as their modal.

Please let me know if there's anything I can do to support this PR and get it merged.

Thank you,
Brian

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] I have run `yarn check` & `yarn build` to confirm there are not any associated errors
- [x] This PR passes the Circle CI checks

### CODE REVIEW

**Comment by Adamj1232** [comment]
@bfriel thank you for this PR! We will get it reviewed soon. We recently released a few web3-onboard packages including the injected-wallets package and that looks like its causing a conflict. If you could resolve when you have a moment that would be great!

**Comment by bfriel** [comment]
Thanks @Adamj1232 ! I see there was a conflict on the injected `package.json` version. I just resolved that. I also see the vercel deployment is failing. I'm not sure if that's related or not. Please let me know if there are other conflicts/low hanging fruit I'm missing here.

**Comment by Adamj1232** [comment]
@bfriel thank you for that! No worries about the vercel error, that is mainly for our docs site. We will get this reviewed shortly

**Comment by Adamj1232** [comment]
@bfriel I pushed a few changes to the PR for building and to fix a couple of errors. Please review when you have a moment.
Also I have updated my Phantom wallet extension on chrome and am still not seeing anything under `window.phantom.ethereum` Is this something that will be rolled out soon?
Screen Shot 2022-11-21 at 12 25 05 PM

**Comment by Adamj1232** [comment]
@bfriel adam@blocknative.com will work or the one associated with my gh profile

**Comment by bfriel** [comment]
Hey @Adamj1232 , you should have received an invite to the email listed on your GH profile! Please let me know if you have any questions or issues with the setup.

**Comment by Adamj1232** [comment]
@bfriel Thank you! I am unable to view the notion page as `Page not found
Either this page doesn't exist or you don't have permission to access it.`
Not totally sure how to get to the chrome extension, any ideas?

**Comment by bfriel** [comment]
> @bfriel Thank you! I think a better email would be [adam@blocknative.com](mailto:adam@blocknative.com) as we use notion as well and I cant be logged into both

Just sent you a new invite to your blacknative email!

**Comment by Adamj1232** [comment]
@bfriel excellent, thank you. Do you have an eta for public release?

**Comment by bfriel** [comment]
> @bfriel excellent, thank you. Do you have an eta for public release?



> adam@blocknative.com

@Adamj1232 Just followed up with you via email.

**Comment by bfriel** [comment]
Hey @Adamj1232, excited to share that Phantom has now opened up its multi-chain waitlist to the public. We're really excited about the [reception to our announcement](https://twitter.com/phantom/status/1597597365774749697) and are working with dApps to ensure we are properly integrated during this current phase of our rollout. Have you had a chance to test this PR with the build we sent you?

**Comment by Adamj1232** [comment]
@bfriel I haven't had a chance a test it with a new feature release we had coming out this week (Transaction Preview package!) but it will be first up on Monday. Thank you again and looking forward to it!

**Comment by bfriel** [comment]
Hey @Adamj1232 thanks so much for your review and for adding those changes! I just recorded a walkthrough video showing how Phantom can connect, sign messages, and send transactions on the four chains we'll support on launch (Ethereum, Ethereum Goerli, Polygon, and Polygon Mumbai): https://www.loom.com/share/86baf8f1be744e548f2cada8887e6c1e

Thanks for submitting that ticket regarding network toggling from within the wallet—we will have that cleaned up for launch 😄

**Comment by Adamj1232** [comment]
@bfriel Excellent, thank you for the video, its very helpful! All looks good to me. As I noted I wont be able to test on Android so will need your confirmation there. Otherwise I think we are good to go.  We will want to wait to release when Phantom goes live, maybe coordinate some sweet marketing. Are our bizDev teams connected?

**Comment by bfriel** [comment]
@Adamj1232 Awesome! Can't wait for this to go live. What is the best email for us to reach out to regarding bizdev/marketing? I will have our growth team reach out.

We're currently on track to release our first batch of beta codes as early as next week. It would be awesome to have these users try out dApps using web3-onboard!

**Comment by Adamj1232** [comment]
@bfriel Mobeen(mobeen@blocknative.com) would be the best contact for this! We will target a package release based on when the support/announcement goes live.

**Comment by Adamj1232** [comment]
Hey @bfriel we have a target release date of the alpha versioned Phantom package set for Monday! We will then release the official package (sans the alpha tag closer to full Phantom evm support). In preparation can you do me a favor and pull in the latest develop(we will be doing a release later today so tomorrow might be better for this). Then a final round of testing on your end, (especially transactions and Android support as I can't test those) and we should be good to go. Excited to get this out!

**Comment by bfriel** [comment]
@Adamj1232 Can't wait! Thank you so much for your help and responsiveness throughout this PR process. I just tested this again today on our internal mobile & extension builds and everything is working great. Can't wait to have our first batch of beta users try this out. Looking forward to Monday!

**Review by Adamj1232 — APPROVED** [review]
Looks good! Thanks again @bfriel for working through this!

**Pull request merged**
