### PR TITLE
[core-v2.13.0-alpha.2, react, vue]: Enhancement - Container el prop for Connect Modal

### PR DESCRIPTION
**Pull request by Adamj1232**
### Description
This PR adds the ability to pass an html container el ID through the W3O init and append the connect modal to that element

Per a slack convo with Gustavo mobile styles will not be changed for this updates as it is out of scope.

```typescript
export type ContainerElements = {
  accountCenter?: string
  connectModal?: string
}
```

If both elements have a containerEl defined each will be appended to the defined container element as seen in img #2

Screen Shot 2023-01-09 at 1 34 26 PM

Screen Shot 2023-01-09 at 1 48 18 PM

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] I have run `yarn file-check`, `yarn type-check` & `yarn build` to confirm there are not any associated errors
- [x] This PR passes the Circle CI checks

### CODE REVIEW

**Review by aaronbarnardsound — APPROVED** [review]

**Comment by omarsy** [comment]
@Adamj1232  Maybe we need also change the behaviour for Hardware wallet. I think we always have modal even if we choose inline

**Comment by Adamj1232** [comment]
> @Adamj1232 Maybe we need also change the behaviour for Hardware wallet. I think we always have modal even if we choose inline

Ah yep we will need to make a similar update for the HW-common package - as this is a separate package it will take some time. As for injected/sdk wallets does this change meet your needs?

**Comment by omarsy** [comment]
@Adamj1232 Yes Thank you I will test it. 🔥
On my side I will put in the same container maybe we can make the container of hw overridable, what do you think ?

**Comment by Adamj1232** [comment]
@omarsy with the update I'm working on the styling/overlay of the HW Account Select modal over the connect modal will be up to the dev to implement. If the same container id is passed to the hw wallet init and containerElements.connectModal they will display next to each other. So it will be up to the dev to control how those are shown using the container elements styling. Just a heads up 😄

**Comment by omarsy** [comment]
@Adamj1232  Thank You.
I see we always have the modal icon and the css related to the modal can we delete it when we are in inline mode
image

**Comment by Adamj1232** [comment]
@omarsy Ah you are referring to the close button/icon on the connect modal? We can add a prop to disable this ability if needed

**Pull request merged**
