### PR TITLE
Feat: Add Universal Profiles extension

### PR DESCRIPTION
**Pull request by andyogaga**
### Description
This adds the LUKSO Universal Profiles Extension to web3-onboard.

image

### Checklist
- [x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x] Check the box that allows repo maintainers to update this PR
- [x] Test locally to make sure this feature/fix works
- [x] Run `yarn check-all` to confirm there are not any associated errors
- [x] Confirm this PR passes Circle CI checks
- [x] Add or update relevant information in the documentation

### Docs Checklist
- [x] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
- [x] Add/update the appropriate package README (if applicable)
- [x] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) (if applicable)
- [x] Add/update the related package in the `docs/package.json` file (if applicable)

### If this PR includes changes to add an injected wallet or SDK wallet module: 
Please complete the following using the internal demo package.
To run this demo use the command `yarn && yarn dev` to get the project running at `http://localhost:8080/`

#### Tests with demo app (injected)
- [x] send transaction
- [x] switch chains
- [ ] sign message
- [ ] sign typed message
- [x] disconnect

#### Tests with demo app (SDK)
- [ ] send transaction
- [ ] switch chains
- [ ] sign message
- [ ] sign typed message
- [ ] disconnect

### CODE REVIEW

**Comment by Adamj1232** [comment]
@andyogaga we are no longer supporting separate packages for injected wallets as it adds a lot of extra maintenance and upkeep from our dev team when underlying packages update. All the same functionality(display when unavailable, display download link) is available through the injected module as well. When you have a moment could you please remove the new UP module from this PR? Thanks!

**Comment by taylorjdawson** [comment]
> andyogaga

@andyogaga in addition to @Adamj1232's suggestion can you also merge latest develop and resolve conflicts, thanks!

**Comment by Adamj1232** [comment]
@andyogaga friendly ping on the above notes. If they aren't addressed by next week we will close this PR as stale.

**Comment by andyogaga** [comment]
> @andyogaga friendly ping on the above notes. If they aren't addressed by next week we will close this PR as stale.

Thanks @Adamj1232 for the reminder. We instead opted to add our package to the custom injected modules as advised.

Hence we will be closing this PR since we can actually use web3-onboard without making the PR.

Thanks again.

**Pull request closed without merging**
