### PR TITLE
fix: Add option to hide the where is my wallet notice

### PR DESCRIPTION
**Pull request by usame-algan**
### Description
Adds an option to hide the "Where is my wallet" notice

Screenshot 2023-06-27 at 11 25 03

### Checklist
- [x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x] Check the box that allows repo maintainers to update this PR
- [x] Test locally to make sure this feature/fix works
- [x] Run `yarn check-all` to confirm there are not any associated errors
- [x] Confirm this PR passes Circle CI checks
- [x] Add or update relevant information in the documentation

### Docs Checklist
- [x] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
- [x] Add/update the appropriate package README (if applicable)
- [x] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) (if applicable)
- [x] Add/update the related package in the `docs/package.json` file (if applicable)

### If this PR includes changes to add an injected wallet or SDK wallet module: 
Please complete the following using the internal demo package.
To run this demo use the command `yarn && yarn dev` to get the project running at `http://localhost:8080/`

#### Tests with demo app (injected)
- [x] send transaction
- [x] switch chains
- [x] sign message
- [x] sign typed message
- [x] disconnect

#### Tests with demo app (SDK)
- [ ] send transaction
- [ ] switch chains
- [ ] sign message
- [ ] sign typed message
- [ ] disconnect

### CODE REVIEW

**Review by iamacook — APPROVED** [review]
LGTM!

**Comment by usame-algan** [comment]
@Adamj1232 we are currently patching this on our side. Anything I can do to move this PR forward?

**Comment by Adamj1232** [comment]
@usame-algan thanks for this PR - I am discussing supporting this with the team and will update shortly!
In the mean time can you bump the alpha version within the version tag(`x.x.x-alpha.x` the final `x`) of `packages/core/package.json` when you have a moment?

**Review by Adamj1232 — APPROVED** [review]
@usame-algan thank you for the PR!
I tested locally and works as expected. Added some test code, enhanced docs and formatted. Will merge after CI checks finalize!

**Pull request merged**
