### PR TITLE
support D'CENT Wallet on PC 

### PR DESCRIPTION
**Pull request by KyungeunKim**
### Description
- preconditions
   - Download 'dcent-bridge' program & install from https://bridge.dcentwallet.com/v2/download
   
Screen Shot 2022-02-14 at 1 29 46 PM

- You can connect D'CENT biometric wallet on PC 
Screen Shot 2022-02-14 at 1 31 08 PM

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks (if **merging a fork** run `yarn` with node version 12.22.7 to ensure no errors)

### CODE REVIEW

**Comment by KyungeunKim** [comment]
Some lint errors are occurred. But the code is not my code. So I didn't fix remaining lint error.
What should I do?

**Comment by Adamj1232** [comment]
@KyungeunKim thank you for your PR! We are pushing a rebrand today, can you handle the conflicts and sync with develop. I will try to get your changes into the next release. 
Are you part of the D'Cent team? If so I would love to get your teams Business Dev lead connected with ours
Feel free to contact me through my email adam@blocknative.com

**Comment by KyungeunKim** [comment]
@Adamj1232 
I'm engineer at D'CENT. I forwarded your email to our business team. You'll probably get in touch soon. :)

I resolved conflicts and synced your develop. (But there's still an error where it's not my code.)

**Comment by Adamj1232** [comment]
@KyungeunKim thank you for that! Looking forward to connecting.
Since this is a hardware wallet integration we will need to test with a hardware wallet before adding to Onboard (and then to Onboard V2 which is in beta). 
Any chance your team could send a wallet to a dev or two so that we can test the PR implementation and prepare a version for Onboard V2?

**Comment by aaronbarnardsound** [comment]
Hey @KyungeunKim this PR closed automatically when we updated our branches for version 2. Can you please reopen and target the `v1-onboard` branch?

**Comment by Adamj1232** [comment]
@KyungeunKim if you could create a pull for the same changes but with a D'CENT module(see other hardware wallets as examples) for the Onboard V2 release that would be great as well! Cheers!

**Pull request closed without merging**
