### PR TITLE
Allow partial override of i18n per new docs

### PR DESCRIPTION
**Pull request by wbt**
### Checklist
- [x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x] Check the box that allows repo maintainers to update this PR
- [x] Test locally to make sure this feature/fix works
- [x] Run `yarn check-all` to confirm there are not any associated errors
- [x] Confirm this PR passes Circle CI checks (cannot be done without at least a cursory review to verify the PR isn't exfiltrating secrets)
- [x] Add or update relevant information in the documentation

### Docs Checklist
- No update to docs as this just brings code typing more in line with current documentation.

### CODE REVIEW

**Comment by Adamj1232** [comment]
@wbt please add a description to this PR as to why this change is required, along previous/expected behavior.
In addition to commenting a stackoverflow link please provide readable information

**Review by Adamj1232 — CHANGES_REQUESTED** [review]
@wbt please add a description to this PR as to why this change is required, along previous/expected behavior.
In addition to commenting a stackoverflow link please provide readable information

**Comment by Adamj1232** [comment]
@wbt friendly ping here on the comment above 😄

**Comment by wbt** [comment]
The documentation/discussion is in the linked issue [here](https://github.com/blocknative/web3-onboard/issues/1632#issuecomment-1521869917) with context.

**Comment by leightkt** [comment]
@wbt will you please add a comment to type.ts- I suggested something, feel free to tweak. Otherwise- looking good

**Comment by leightkt** [comment]
@wbt just a note on the package version
Will you please also update docs/package.json, packages/react/package.json, and packages/vue/package.json to the new alpha version of core i.e.
change "@web3-onboard/core": "^2.17.0" to "@web3-onboard/core": "^2.17.1-alpha.1" in those files. 

After that- should be good to go!

**Comment by leightkt** [comment]
included in https://github.com/blocknative/web3-onboard/pull/1698

**Pull request closed without merging**
