### PR TITLE
fix: use new Inter URL font instead of now invalid old one

### PR DESCRIPTION
**Pull request by ghivert**
### Description

Because of the change of https://rsms.me few hours ago, old Inter font files URL are now returning a 404 error. This PR uses the new font file URL for the Inter, in order to get the old behavior working.
This is especially important because if a web-app is using Web3-Onboard and Inter in it's files, there's chances that the Inter version of Web3-Onboard will take precedence over the font file loaded by the app.

This should also includes a new release after the merge.

Important to note, there's no changes in the demo, everything is working great. No need to add a screenshot, because there's actually no differences at all.

### Checklist
- [x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x] Check the box that allows repo maintainers to update this PR
- [x] Test locally to make sure this feature/fix works
- [x] Run `yarn check-all` to confirm there are not any associated errors
- [x] Confirm this PR passes Circle CI checks
- [x] Add or update relevant information in the documentation

### Docs Checklist
- [x] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
- [x] Add/update the appropriate package README (if applicable)
- [x] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) (if applicable)
- [x] Add/update the related package in the `docs/package.json` file (if applicable)

### If this PR includes changes to add an injected wallet or SDK wallet module: 
Please complete the following using the internal demo package.
To run this demo use the command `yarn && yarn dev` to get the project running at `http://localhost:8080/`

#### Tests with demo app (injected)
- [ ] send transaction
- [ ] switch chains
- [ ] sign message
- [ ] sign typed message
- [ ] disconnect

#### Tests with demo app (SDK)
- [ ] send transaction
- [ ] switch chains
- [ ] sign message
- [ ] sign typed message
- [ ] disconnect

### CODE REVIEW

**Comment by RronKurtishi** [comment]
What's the status with this fix?

**Comment by lomocc** [comment]
As a library, the font selection should be given to the user. There is no need for automatic remote loading.Not to mention that this file address is no longer valid.

**Comment by Adamj1232** [comment]
Working on this update and should be available for alpha shortly.
@lomocc font selection is in the hands of the external developers, please see code section [here](https://github.com/blocknative/web3-onboard/blob/ca2b510dbb463da6f756795f1446ee178060f44d/packages/core/src/index.ts#L278)

**Comment by Adamj1232** [comment]
Closing in favor of https://github.com/blocknative/web3-onboard/pull/2092
Thank you for opening this PR!

**Pull request closed without merging**
