### PR TITLE
Update WalletConnect `eth_RequestAccounts` flow along with update WC deps and add new optional params

### LINKED ISSUE #1608: [Bug]: walletconnect v2 not connecting or working
### Current Behavior

When creating a WC2 connection, after pasting the wc2 uri in the wallet the screen stay stuck on the connect wallet screen

### Expected Behavior

a connection should be created and be able to send txs

### Steps To Reproduce

initiate a walletconnect here:
https://onboard.blocknative.com/examples/connect-wallet

paste the uri in the wallet here (official wc2 demo wallet):
https://react-web3wallet.vercel.app/walletconnect

result: demo wallet doesnt detect connection
onboard app stays on connect wallet.

note:
- if you close onboard popup and press on connect again, it will show like it is connected, but only on onboard side. not possible to send any requests.
- the bug has been confirmed also this wallet: wallet.gooddollar.org and this app: https://good-swap-4wotazy07-gooddollarteam.vercel.app/

### What package is effected by this issue?

@web3-onboard/walletconnect

### Is this a build or a runtime issue?

Runtime

### Package Version

latest

### Node Version

_No response_

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Anything else?

_No response_

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by Adamj1232**
#### Update WC deps:
```
"@walletconnect/ethereum-provider": "2.4.10" -> "2.5.4"
```

#### Add new optional params `qrModalOptions?: Web3ModalConfig` exposed with the new WC dep:
```ts
type WalletConnectOptions = {
  bridge?: string // default = 'https://bridge.walletconnect.org'
  qrcodeModalOptions?: {
    mobileLinks: string[] // set the order and list of mobile linking wallets
  }
  connectFirstChainId?: boolean // if true, connects to the first network chain provided
  /**
   * Optional function to handle WalletConnect URI when it becomes available
   */
  handleUri?: (uri: string) => Promise<unknown>
} & (
  | {
      /**
       * Defaults to version: 1 - this behavior will be deprecated after the WalletConnect v1 sunset
       */
      version?: 1
    }
  | {
      /**
       * Project ID associated with [WalletConnect account](https://cloud.walletconnect.com)
       */
      projectId: string

      /**
       * Defaults to version: 1 - this behavior will be deprecated after the WalletConnect v1 sunset
       */
      version: 2
      /**
       * List of Required Chain(s) ID for wallets to support in number format (integer or hex)
       * Defaults to [1] - Ethereum
       * The chains defined within the web3-onboard config will define the
       * optional chains for the WalletConnect module
       */
      requiredChains?: number[] | undefined
      /**
       * `undefined` by default, see https://docs.walletconnect.com/2.0/web3modal/options
       */
      qrModalOptions?: Web3ModalConfig
    }
)
```

Fixes #1608 

### Checklist
- [ ] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [ ] Check the box that allows repo maintainers to update this PR
- [ ] Test locally to make sure this feature/fix works
- [ ] Run `yarn check-all` to confirm there are not any associated errors
- [ ] Confirm this PR passes Circle CI checks
- [ ] Add or update relevant information in the documentation

### CODE REVIEW

**Review by leightkt — COMMENTED** [review]
When trying to connect an infinity wallet via walletconnect on the demo- I get the following errors in the console: 
Screenshot 2023-03-31 at 3 04 50 PM

Is there another way I can test this update?

**Comment by Adamj1232** [comment]
> When trying to connect an infinity wallet via walletconnect on the demo- I get the following errors in the console: Screenshot 2023-03-31 at 3 04 50 PM
> 
> Is there another way I can test this update?
@leightkt 
Not all wallets(in fact not very many) support walletconnect v2 fully. You can try Trust Wallet mobile or use the WC teams recommended testing tool: https://react-web3wallet.vercel.app/walletconnect

**Comment by Adamj1232** [comment]
@leightkt for a more complete list of larger wallets that do and dont support walletconnect v2 checkout - https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595

**Review by leightkt — APPROVED** [review]
Was able to successfully connect wallet from https://react-web3wallet.vercel.app/walletconnect to demo

**Pull request merged**
